import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { promises as fs } from "fs";
import { ConfigProvider } from "@/store/config-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const configResp = await fetch(
    new URL("/api/config", process.env.NEXT_PUBLIC_URL_ORIGIN),
    {
      method: "GET",
      cache: "no-cache",
    }
  ).then((res) => res.json());

  const config = configResp.data.config
    ? configResp.data.config
    : {
        primary: "white",
        title: "Niceboard",
        description: "A nice dashboard",
      };
  console.log({ config1: config });

  return (
    <html lang="en">
      <ConfigProvider config={config}>
        <body className={inter.className}>{children}</body>
      </ConfigProvider>
    </html>
  );
}
